### ISSUE TITLE
Convert star * import to regular import

### ISSUE THREAD

**Issue by angelofallars** [algodrip/pomodrip#10]
`main.py` imports tkinter and time using * imports. This will pose an issue once we add more and more features (and thus modules) to Pomodrip. If a function from Tkinter and another function from a module have the same name, they will clash and cause errors. Changing to regular imports will improve the readability of code as well.

## Suggested actions

- Change `from tkinter import *` to `import tkinter as tk`
- Change `from timer import *` to just `import timer`
- Update the functions that use tkinter to reflect the changes above like `StringVar()` to `tk.StringVar()`

**Comment by nafumie** [comment]
Also cross-reference to this: https://www.python.org/dev/peps/pep-0008/#imports
