### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by angelofallars** [algodrip/pomodrip#18]
We should add a license to our project like the MIT license or the GNU license. Let's discuss about the licensing here.

**Comment by nafumie** [comment]
I guess this is suitable? Thoughts?
https://choosealicense.com/licenses/gpl-3.0/

**Comment by angelofallars** [comment]
Yeah, GPLv3 looks good to me

**Comment by Neoloopy** [comment]
Same, GNU GPLv3 sounds like it fits with what we're going for
